<?xml version="1.0" encoding="utf-8"?><testsuites name="pytest tests"><testsuite name="pytest" errors="0" failures="0" skipped="2" tests="9" time="3.938" timestamp="2025-09-29T19:20:02.438317+08:00" hostname="606deMacBook-Air.local"><testcase classname="" name="tests.unit.test_data_quality_system" time="0.000"><skipped message="collection skipped">('/Users/a606/cloud_function_source/tests/unit/test_data_quality_system.py', 24, "Skipped: 数据质量检查模块导入失败: cannot import name 'DataQualityIssue' from 'data_quality_checker' (/Users/a606/cloud_function_source/data_quality_checker.py)")</skipped></testcase><testcase classname="" name="tests.unit.test_monitoring_system" time="0.000"><skipped message="collection skipped">('/Users/a606/cloud_function_source/tests/unit/test_monitoring_system.py', 30, "Skipped: 监控模块导入失败: No module named 'python.health_alert_system'")</skipped></testcase><testcase classname="tests.unit.test_data_processing.TestDataProcessing" name="test_data_aggregation" time="0.002" /><testcase classname="tests.unit.test_data_processing.TestDataProcessing" name="test_data_cleaning" time="0.000" /><testcase classname="tests.unit.test_data_processing.TestDataProcessing" name="test_data_export" time="0.000" /><testcase classname="tests.unit.test_data_processing.TestDataProcessing" name="test_data_transformation" time="0.001" /><testcase classname="tests.unit.test_data_processing.TestDataProcessing" name="test_data_validation" time="0.000" /><testcase classname="tests.unit.test_data_processing.TestDataProcessing" name="test_real_time_processing" time="0.001" /><testcase classname="tests.unit.test_api_connection" name="test_api_connection" time="0.001" /></testsuite></testsuites>